spring:
  config:
    activate:
      on-profile: test
  # Cấu hình file upload cho test
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
      file-size-threshold: 2KB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: ${API_URL:DUMMY-API-URL}
    title: API Document
    version: 1.0.0