spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/plants_support?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: ${API_URL:https://plantcare.id.vn/api}
    title: API Document
    version: 1.0.0

# AI Configuration
openai:
  api:
    key: ${OPENAI_API_KEY}

openrouter:
  api:
    key: ${OPENROUTER_API_KEY}
    base-url: https://openrouter.ai/api/v1
    model: google/gemini-pro
    max-tokens: 1000

# App Configuration
app:
  base-url: ${APP_BASE_URL:https://plantcare.id.vn}

# Payment Configuration
vnpay:
  tmn-code: ${VNPAY_TMN_CODE:IZVMM9RJ}
  hash-secret: ${VNPAY_HASH_SECRET:0PS4G1NU0ZOFUGWQLHNZTFVLWT23RAJQ}
  payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: https://plantcare.id.vn/api/payment/vnpay-return
  ipn-url: https://plantcare.id.vn/api/payment/vnpay-ipn
  merchant-admin-url: https://sandbox.vnpayment.vn/merchantv2/

# PayPal Configuration
paypal:
  client:
    id: ${PAYPAL_CLIENT_ID}
    secret: ${PAYPAL_CLIENT_SECRET}
  mode: sandbox

# Security Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

# File Upload Configuration
file:
  upload-dir: /var/www/uploads/
  max-size: 20MB

# Logging Configuration
logging:
  level:
    com.plantcare_backend: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"