server:
  port: 8080

spring:
  application:
    name: tay-java-app
  profiles:
    active: @spring.profiles.active@

  # Cấu hình file upload
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health: # config for EKS
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 5s
        enabled: true

# Logging
logging:
  level:
    root: INFO
    web: OFF
    org.springframework: INFO
    org.apache: OFF
    kafka: OFF
    com.plantcare_backend: DEBUG
    org.springframework.web: DEBUG