spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: ${API_URL:DUMMY-API-URL}
    title: API Document
    version: 1.0.0

# AI Configuration
openai:
  api:
    key: ${OPENAI_API_KEY}

openrouter:
  api:
    key: ${OPENROUTER_API_KEY}
    base-url: https://openrouter.ai/api/v1
    model: google/gemini-pro
    max-tokens: 1000

# App Configuration
app:
  base-url: ${APP_BASE_URL:http://40.81.23.51}