server:
  port: 8080

spring:
  application:
    name: tay-java-app
  profiles:
    active: @spring.profiles.active@

  # Cấu hình file upload
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}

  # Cấu hình Jackson timezone
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss

  # Cấu hình JPA timezone
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

# PlantCare Configuration
plantcare:
  base-url: ${PLANTCARE_BASE_URL:http://localhost:4200}
  scheduler:
    cron: ${PLANTCARE_SCHEDULER_CRON:0 0 8 * * ?}
    timezone: ${PLANTCARE_SCHEDULER_TIMEZONE:Asia/Ho_Chi_Minh}
    batch-size: ${PLANTCARE_BATCH_SIZE:100}
  email:
    retry-attempts: ${PLANTCARE_EMAIL_RETRY_ATTEMPTS:3}
    retry-delay: ${PLANTCARE_EMAIL_RETRY_DELAY:1000}
  default-schedules:
    watering:
      frequency-days: ${PLANTCARE_DEFAULT_WATERING_DAYS:3}
    fertilizing:
      frequency-days: ${PLANTCARE_DEFAULT_FERTILIZING_DAYS:30}
  # AI Configuration
  ai:
    plant-id:
      api-key: ${PLANTCARE_AI_PLANT_ID_API_KEY:sgG4eDNnSC87ATYjZllplm8ktLG54LAhai1QCbY13nla1x4fap}
      base-url: ${PLANTCARE_AI_PLANT_ID_BASE_URL:https://plant.id/api/v3}
      timeout: ${PLANTCARE_AI_TIMEOUT:30000}

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health: # config for EKS
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 5s
        enabled: true

  # VIP Configuration
  vip:
    subscription:
      check-interval: "0 0 * * * ?"  # Mỗi giờ
      reminder-interval: "0 0 8 * * ?"  # 8h sáng mỗi ngày
      reminder-days-before: 7  # Nhắc nhở 7 ngày trước khi hết hạn
      auto-renewal: false  # Tắt auto renewal mặc định

# Azure Storage Configuration
azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME:plantcare-storage}
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME:plantcarestorage}
    blob-endpoint: ${AZURE_STORAGE_BLOB_ENDPOINT:https://plantcarestorage.blob.core.windows.net}
    max-connections: 50
    connection-timeout: 30000
    read-timeout: 30000

# Logging
logging:
  level:
    root: INFO
    web: OFF
    org.springframework: INFO
    org.apache: OFF
    kafka: OFF
    com.plantcare_backend: DEBUG
    org.springframework.web: DEBUG