name: Build and Deploy Spring Boot

on:
  push:
    branches: [ "main", "plantcare-be" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd plantcare-backend
          mvn -B clean package

      - name: List target directory
        run: ls -l plantcare-backend/target

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: plantcare-backend
          path: plantcare-backend/plantcare-backend/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: plantcare-backend

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "plantcare-backend/plantcare-backend/target/*.jar"
          target: "/home/ubuntu/plantcare-backend"

      - name: Restart app on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            pkill -f 'java.*plantcare-backend' || true
            nohup java -jar /home/ubuntu/plantcare-backend/*.jar --spring.profiles.active=prod > app.log 2>&1 &