name: Build and Deploy Spring Boot

on:
  push:
    branches: [ "main", "plantcare-be" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build sẽ tự động chạy test, nếu test fail sẽ dừng tại đây
      - name: Build with Maven
        run: |
          cd plantcare-backend
          mvn -B clean package
      - name: List target directory
        run: ls -l plantcare-backend/target

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: plantcare-backend
          path: plantcare-backend/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: plantcare-backend

      # Backup JAR cũ trước khi deploy
      - name: Backup old JAR on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          script: |
            if [ -f /opt/plantcare-app/plantcare-backend-0.0.1-SNAPSHOT.jar ]; then
              cp /opt/plantcare-app/plantcare-backend-0.0.1-SNAPSHOT.jar /opt/plantcare-app/plantcare-backend-0.0.1-SNAPSHOT.jar.bak
            fi
      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          source: "plantcare-backend/target/*.jar"
          target: "/opt/plantcare-app"

      - name: Restart app on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          script: |
            sudo systemctl stop plantcare-app || true
            sudo systemctl start plantcare-app
            sudo systemctl status plantcare-app
      # Rollback nếu deploy lỗi
      - name: Rollback if deploy failed
        if: failure()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          script: |
            if [ -f /opt/plantcare-app/plantcare-backend-0.0.1-SNAPSHOT.jar.bak ]; then
              mv /opt/plantcare-app/plantcare-backend-0.0.1-SNAPSHOT.jar.bak /opt/plantcare-app/plantcare-backend-0.0.1-SNAPSHOT.jar
              sudo systemctl restart plantcare-app
            fi
